//
//  WalletModels.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 18/03/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Wallet
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum GetBraintreeToken
    {
        struct Request
        {
        }
        struct Response
        {
            let error: Error?
            let token: String
        }
        struct ViewModel
        {
            let error: Error?
            let token: String
        }
    }
    
    enum PerformTransaction
    {
        struct Request
        {
            let nonce: String
            let amount: String
        }
        struct Response
        {
            let error: Error?
            let currentUser: CurrentUser?
            let userTransactions: [Transaction]?
        }
        struct ViewModel
        {
            let error: Error?
            let currentUser: CurrentUser?
            let userTransactions: [Transaction]?
        }
    }
    
    
    enum LoadUserInformation {
        struct Request
        {
        }
        struct Response
        {
            let error: Error?
            let currentUser: CurrentUser?
            let userTransactions: [Transaction]?
        }
        struct ViewModel
        {
            let error: Error?
            let currentUser: CurrentUser?
            let userTransactions: [Transaction]?
        }
    }
 
    
}
