//
//  ProfileInteractor.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 01/04/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic
{
    func doSomething(request: Profile.Something.Request)
    func logoutButtonPressed(request: Profile.LogoutButtonPressed.Request)
}

protocol ProfileDataStore
{
    //var name: String { get set }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore
{
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Profile.Something.Request)
    {
        worker = ProfileWorker()
        worker?.doSomeWork()
        
        let response = Profile.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func logoutButtonPressed(request: Profile.LogoutButtonPressed.Request) {
        worker = ProfileWorker()
        worker?.logoutUser(completion: {
            
            let response = Profile.LogoutButtonPressed.Response()
            self.presenter?.presentLogoutButtonPressed(response: response)
        })
    }
}
