//
//  PaymentInteractor.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 18/03/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentBusinessLogic
{
    func doSomething(request: Payment.Something.Request)
}

protocol PaymentDataStore
{
    //var name: String { get set }
}

class PaymentInteractor: PaymentBusinessLogic, PaymentDataStore
{
    var presenter: PaymentPresentationLogic?
    var worker: PaymentWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Payment.Something.Request)
    {
        worker = PaymentWorker()
        worker?.doSomeWork()
        
        let response = Payment.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
