//
//  PaymentPresenter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 18/03/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentPresentationLogic
{
    func presentSomething(response: Payment.Something.Response)
}

class PaymentPresenter: PaymentPresentationLogic
{
    weak var viewController: PaymentDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Payment.Something.Response)
    {
        let viewModel = Payment.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
