//
//  AddCreditPresenter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 20/03/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddCreditPresentationLogic
{
    func presentSomething(response: AddCredit.Something.Response)
}

class AddCreditPresenter: AddCreditPresentationLogic
{
    weak var viewController: AddCreditDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: AddCredit.Something.Response)
    {
        let viewModel = AddCredit.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
