//
//  RegisterWorker.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 29/02/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegisterWorker
{
    var repository = Repository.getInstance()
    
    func doSomeWork()
    {
    }
    
    func fetchStatesForCountry(request: Register.FetchStatesForCountry.Request, completionHandler: @escaping ((_ states: [State]) -> Void)) {
        
        let countryCode = request.countryCode
        
        repository.fetchJSONAccessToken {
            self.repository.fetchStatesForCountry(countryCode: countryCode) { (states) in
                completionHandler(states)
            }
        }
    }
    
    func registerNewUser(request: Register.RegisterNewUser.Request, completionHandler: @escaping ((_ error: Error?, _ isThereError: Bool) -> Void)) {
        
        let user = request.userToRegister
        
        repository.registerNewUser(request) { (isError, error) in
            
            // Si existe error al registrar el usuario
            if (isError) {
                completionHandler(error, true)
                return
            } else {
                
                // Si no hay error guardamos el usuario en la base de datos
                self.repository.saveUserToDatabase(user: user) { (error, isError) in
                    
                    // Error al guardar el usuario en la base de datos
                    if (isError) {
                        completionHandler(error, true)
                        return
                    } else {
                        
                        // No hay error al guardar el usuario en la base de datos
                        completionHandler(nil, false)
                    }
                    
                }
            }
            
        }
    }
}
