//
//  RegisterRouter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 29/02/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeLoginScene()
}

protocol RegisterDataPassing
{
    var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
    weak var viewController: RegisterViewController?
    var dataStore: RegisterDataStore?
    
    // MARK: Routing
    
    func routeLoginScene() {
        let destinationVC = LoginViewController()
        navigateToLoginScene(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToLoginScene(source: RegisterViewController, destination: LoginViewController)
    {
        // source.present(destination, animated: true, completion: nil)
        // source.show(destination, sender: self)
        source.navigationController?.popViewController(animated: true)
    }
}
