//
//  ForgottenPasswordInteractor.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 29/02/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgottenPasswordBusinessLogic
{
    func doSomething(request: ForgottenPassword.Something.Request)
    func sendResetPasswordEmail(request: ForgottenPassword.SendForgottenPasswordEmail.Request)
}

protocol ForgottenPasswordDataStore
{
    //var name: String { get set }
}

class ForgottenPasswordInteractor: ForgottenPasswordBusinessLogic, ForgottenPasswordDataStore
{
    var presenter: ForgottenPasswordPresentationLogic?
    var worker: ForgottenPasswordWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ForgottenPassword.Something.Request)
    {
        worker = ForgottenPasswordWorker()
        worker?.doSomeWork()
        
        let response = ForgottenPassword.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func sendResetPasswordEmail(request: ForgottenPassword.SendForgottenPasswordEmail.Request) {
        worker = ForgottenPasswordWorker()
        
        worker?.sendEmailToRecoverPassword(request: request, completionHandler: { [weak self](error) in
            
            let response = ForgottenPassword.SendForgottenPasswordEmail.Response(error: error)
            self?.presenter?.presentResetPasswordEmailSent(response: response)
        })
    }
}
