//
//  ForgottenPasswordPresenter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 29/02/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgottenPasswordPresentationLogic
{
    func presentSomething(response: ForgottenPassword.Something.Response)
}

class ForgottenPasswordPresenter: ForgottenPasswordPresentationLogic
{
    weak var viewController: ForgottenPasswordDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ForgottenPassword.Something.Response)
    {
        let viewModel = ForgottenPassword.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
