//
//  LoginPresenter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 29/02/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSomething(response: Login.Something.Response)
    func presentLoginButtonPressed(response: Login.LoginButtonPressed.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Login.Something.Response)
    {
        let viewModel = Login.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentLoginButtonPressed(response: Login.LoginButtonPressed.Response)
    {
        let viewModel = Login.LoginButtonPressed.ViewModel(error: response.error)
        viewController?.displayLoginButtonPressed(viewModel: viewModel)
    }
}
