//
//  SearchPresenter.swift
//  Nippfy
//
//  Created by Manuel Salvador del Águila on 21/03/2020.
//  Copyright (c) 2020 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentSomething(response: Search.Something.Response)
    func presentIsUserLoggedIn(response: Search.IsUserLoggedIn.Response)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Search.Something.Response)
    {
        let viewModel = Search.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentIsUserLoggedIn(response: Search.IsUserLoggedIn.Response) {
        let viewModel = Search.IsUserLoggedIn.ViewModel(isLoggedIn: response.isLoggedIn)
        viewController?.displayIsUserLoggedIn(viewModel: viewModel)
    }
}
